---
abstract: 'A simple POE Component for monitoring DHCP traffic.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-DHCP-Monitor
requires:
  Net::DHCP::Packet: 0.66
  POE: 1.004
  POE::Wheel::SocketFactory: 0
  perl: 5.006
resources:
  homepage: https://github.com/bingos/poe-component-dhcp-monitor
  repository: https://github.com/bingos/poe-component-dhcp-monitor.git
version: 1.04
